language: android

android:
   components:
   - tools
   - platform-tools
   - android-23
   - build-tools-23.0.3
   - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
   - touch local.properties

script:
  - ./gradlew install
